# 服务器监听端口
server:
  port: 8888

# 配置数据库链接信息、打包后静态目录，关闭jmx监控
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pm_course?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  session:
    store-type: none
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 5MB #限制文件上传大小为5M
  jmx:
    enabled: false
  redis:
    host: localhost
    database: 0
    port: 6379
    password: #默认为空
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 300ms

# mybatis mapper映射路径
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

# 是否打印sql日志，开发时打开（trace），部署时关闭（off）
logging:
  level:
        com.pm.pmapi.mbg.mapper: off
#    com.pm.pmapi.mbg.mapper: trace
        com.pm.pmapi.dao: off
#    com.pm.pmapi.dao: trace

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: pm #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

# 白名单
secure:
  ignored:
    urls: #安全路径白名单，各种静态资源、无需登录即可访问的资源
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /**/*.xls*
      - /**/*.sql
      - /actuator/**
      - /druid/**
      - /api/ums/login
      - /api/ums/register
      - /api/ums/logout
      - /api/ums/vCode


# redis配置
redis:
  database: bbs
  key:
    authCode: 'portal:authCode:'
    user: 'ums:user'
  expire:
    common: 86400 # 24小时
    authCode: 300 # 验证码超期时间，300s

# 上传文件保存路径
upload:
  path: classpath:/upload/