# 服务器监听端口
server:
  port: 8888

# 配置数据库链接信息、打包后静态目录，关闭jmx监控
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pm_course?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  session:
    store-type: none
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
  jmx:
    enabled: false

# mybatis mapper映射路径
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

# 是否打印sql日志，开发时打开（trace），部署时关闭（off）
logging:
  level:
    com.pm.pmapi.mybatis.mapper: off
    com.pm.pmapi.dao: off
